package com.aura.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.UUID

/**
 * MemoryEntry — one record in AURA's long-term memory.
 *
 * Stored in Room DB. Every completed task is embedded and saved here.
 * At planning time, the top-K most semantically similar past tasks are
 * retrieved and injected into the Groq prompt as context.
 *
 * Embeddings are stored as comma-separated floats (Room has no FloatArray column).
 * [EmbeddingEngine] handles serialization / deserialization.
 */
@Entity(tableName = "memory")
data class MemoryEntry(
    @PrimaryKey val id: String = UUID.randomUUID().toString(),

    /** Unix timestamp (ms) when this memory was created. */
    val timestamp: Long = System.currentTimeMillis(),

    /** The original natural-language goal. */
    val goal: String,

    /** "success" | "failure" | "cancelled" */
    val outcome: String,

    /** Primary app package used (e.g. "com.whatsapp"). */
    val appUsed: String,

    /**
     * JSON array of semantic tags extracted from the goal.
     * e.g. ["messaging", "rahul", "whatsapp"]
     */
    val tags: String,

    /**
     * 384-dim sentence embedding stored as comma-separated floats.
     * Generated by [EmbeddingEngine] using a lightweight on-device model.
     * Empty string if embedding generation failed.
     */
    val embedding: String = "",

    /** How many times this memory has been retrieved and used. */
    val retrievalCount: Int = 0,

    /**
     * Optional structured data for smart suggestions.
     * e.g. {"contact": "Rahul", "amount": "500"}  for payment tasks.
     */
    val extraData: String = "{}"
)
